basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Example Go API using Zero One Group's monorepo template
  title: Zero One Group News
  version: "1.0"
paths: {}
swagger: "2.0"
