flowchart TD
    Root["/api"] --> Version["/v1"]
    Version --> Articles["/articles"] & Topics["/topics"]
    Topics --> TopicsGet["GET"] & TopicsPost["POST"] & TopicId["/:topic_id"]
    TopicId --> TopicIdGet["GET"] & TopicIdPatch["PUT"] & TopicIdDelete["DELETE"] & TopicArticles["/articles"]
    TopicArticles --> TopicArticlesGet["GET"]
    Articles --> ArticlesGet["GET"] & ArticlesPost["POST"] & ArticleId["/:article_id"]
    ArticleId --> ArticleIdGet["GET"] & ArticleIdPatch["PUT"] & ArticleIdDelete["DELETE"] & ArticleTopics["/topics"]
    ArticleTopics --> ArticleTopicsGet["GET"] & ArticleTopicsPut["PUT"] & ArticleTopicsId["/:topic_id"]
    ArticleTopicsId --> ArticleTopicsIdPost["POST"] & ArticleTopicsIdDelete["DELETE"]

     Root:::Sky
     Root:::Aqua
     Version:::Sky
     Version:::Aqua
     Articles:::Aqua
     Articles:::Sky
     Topics:::Aqua
     Topics:::Sky
     TopicId:::Rose
     TopicArticles:::Peach
     ArticleId:::Rose
     ArticleTopics:::Peach
     ArticleTopicsId:::Ash
    classDef Aqua stroke-width:1px, stroke-dasharray:none, stroke:#46EDC8, fill:#DEFFF8, color:#378E7A
    classDef Sky stroke-width:1px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C
    classDef Rose stroke-width:1px, stroke-dasharray:none, stroke:#FF5978, fill:#FFDFE5, color:#8E2236
    classDef Peach stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    classDef Ash stroke-width:1px, stroke-dasharray:none, stroke:#999999, fill:#EEEEEE, color:#000000
