name: Test Go App

on:
  push:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb?sslmode=disable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Install dependencies
        working-directory: ./apps/zog-news
        run: go mod download

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U testuser -d testdb; then
              echo "PostgreSQL is ready"
              break
            fi
            sleep 1
          done

      - name: Run tests
        working-directory: ./apps/zog-news
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: go test ./...
